### ISSUE TITLE
Crash after granting then denying Contacts permission

### ISSUE THREAD

**Issue by jkreiser** [googlesamples/android-RuntimePermissions#10]
- click "Show and add contacts"
- allow Contacts permission
- add some contacts and show them
- task-switch to Settings and deny that permission
- task-switch back to the app and immediately try to show the contacts again
- app crashes:

10-29 12:40:09.805  27646-27694/com.example.android.system.runtimepermissions E/AndroidRuntime﹕ FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.example.android.system.runtimepermissions, PID: 27646
    java.lang.RuntimeException: An error occurred while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:142)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{f375bd7 27646:com.example.android.system.runtimepermissions/u0a100} (pid=27646, uid=10100) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
            at android.os.Parcel.readException(Parcel.java:1599)
            at android.os.Parcel.readException(Parcel.java:1552)
            at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
            at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
            at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
            at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
            at android.content.ContentResolver.query(ContentResolver.java:475)
            at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:27)
            at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:56)
            at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:114)
            at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
            at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)

**Comment by keyboardsurfer** [comment]
Internal: 26814452

**Comment by nAkhmedov** [comment]
How to fix this issue?

**Comment by ghost** [comment]
Android 6.0 and above require runtime permission.you should add manually in code.

**Comment by parasg97** [comment]
How fix this isssue?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
